version: '3.8'
services:
  db:
    image: postgres:16
    container_name: postgres
    env_file:
      - db.env
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
  backend:
    build: .
    container_name: backend
    env_file:
      - db.env
      - backend.env
    ports:
      - '8080:8080'
    depends_on:
      - db

volumes:
  db-data: